### ISSUE TITLE
TYPO in code?

### ISSUE THREAD

**Issue by mru4913** [VITA-Group/TENAS#2]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/31579276/109781152-a0a84480-7c42-11eb-8d49-6e11a6cd9f4c.png">
Sorry to bother you guys again. I am trying to reproduce your work.  I think this is a typo "self.op_name"

**Comment by chenwydj** [comment]
Hi @mru4913 !

You are right. I have fixed this. Thank you very much!
