### ISSUE TITLE
For DARTS search space-with Imagenet-1k dataset, the time reported in the paper (4 hours) is not even close when replicated.

### ISSUE THREAD

**Issue by oshindutta** [VITA-Group/TENAS#20]
For DARTS search space-with Imagenet-1k dataset, the time reported in the paper (4 hours) is not even close when replicated on Tesla v100 (it should be lower than 4 hours as v100 is much faster than 1080 Ti). 

It takes around 10 hours with the batch_size 24 (as mentioned in the code). 

What do you think might be the issue?

**Comment by chenwydj** [comment]
Hi @oshindutta,

Thanks for your interest in our work!

The "four GPU hours" is verified multiple times, so it is valid.

Possible reasons might be on other hardware sides: the CPU load, the I/O speed of your hard disk, etc.
