### ISSUE TITLE
Question about training time?

### ISSUE THREAD

**Issue by mru4913** [VITA-Group/TENAS#3]
I m training CIFAR10 dataset on a machine with a GPU(2080Ti). 

According to the paper, 
> TE-NAS achieves a test error of 2.63%, ranking among the top of recent NAS results, but meanwhile largely reduces the search cost to only 30 minutes.

However, it takes me about 1hr to execute 80% of the process. 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/31579276/109789105-f41e9080-7c4a-11eb-99bc-6c19c3b0d898.png">

The command I use is `python prune_launch.py --space darts --dataset cifar10 --gpu 1` following the instructions. Do I miss anything during the training?

**Comment by mru4913** [comment]
Or maybe you mean 0.5 GPU days in the table?

**Comment by mru4913** [comment]
`Traceback (most recent call last):
  File "./prune_tenas.py", line 490, in <module>
    main(args)
  File "./prune_tenas.py", line 429, in main
    prune_number=xargs.prune_number
  File "./prune_tenas.py", line 147, in prune_func_rank
    ntk_all = sorted(ntk_all, key=lambda tup: round_to(tup[0], precision), reverse=True)  # descending: we want to prune op to decrease ntk, i.e. to make ntk_origin > ntk
  File "./prune_tenas.py", line 147, in <lambda>
    ntk_all = sorted(ntk_all, key=lambda tup: round_to(tup[0], precision), reverse=True)  # descending: we want to prune op to decrease ntk, i.e. to make ntk_origin > ntk
  File "./prune_tenas.py", line 60, in round_to
    power = math.floor(math.log(number, 10)) + 1
ValueError: cannot convert float NaN to integer`

This should consider 'nan'.

**Comment by chenwydj** [comment]
Hi @mru4913! Thanks for the questions!

1. For the search time cost, please refer to our Table 2. I have just updated the main text and submitted to arxiv. Thanks for pointing out!
2. I just pushed the updates to the code to consider 'nan' value. Thanks!
