### ISSUE TITLE
Where to find architectures searched for ImageNet

### ISSUE THREAD

**Issue by MingLin-home** [VITA-Group/TENAS#5]
Nice work!
I really enjoy your work! I am wondering whether you have any plans to release the architectures searched for ImageNet in your paper. Thanks ahead!

**Comment by chenwydj** [comment]
Hi @MingLin-home 

Thank you for your interest in our work!

If you go the the ["Evaluation" section](https://github.com/VITA-Group/TENAS#2-evaluation), you can find our [searched genotypes here](https://github.com/chenwydj/DARTS_evaluation/blob/main/genotypes.py#L77).
