### ISSUE TITLE
Segment fault when execute prune_launch.py in bash, while no error in Pycharm

### ISSUE THREAD

**Issue by llnb101** [VITA-Group/TENAS#6]
### Run in command line. 
![image](https://user-images.githubusercontent.com/72189285/115245001-1155e280-a157-11eb-9f22-0995a496c203.png)
### Run in Pycharm by editing configuration. 
![image](https://user-images.githubusercontent.com/72189285/115245234-4eba7000-a157-11eb-8d80-3452c4e8da50.png)

**Comment by chenwydj** [comment]
Hi @llnb101,

Thank you for your interest in our work!

Actually, I have no idea about this segmentation fault error. I personally do not use pycharm and all my experiments are done in terminal.
