### ISSUE TITLE
Please tell me which paper does this algorithm come from(in linear_region_counter.py , line 130, def calc_LR())

### ISSUE THREAD

**Issue by trestad** [VITA-Group/TENAS#7]
![image](https://user-images.githubusercontent.com/55476033/115349837-eca94b80-a1e6-11eb-8f9a-35da96b24fdb.png)

**Comment by chenwydj** [comment]
Hi @trestad,

Thank you for your interest in our work!

We developed this algorithm. The definition of linear region is from this paper: https://arxiv.org/pdf/2006.00978.pdf

I also added some comments to make this function more readable: https://github.com/VITA-Group/TENAS/blob/main/lib/procedures/linear_region_counter.py#L130
