### ISSUE TITLE
Linear_Region_Collector

### ISSUE THREAD

**Issue by Yasaman-Haghighi** [VITA-Group/TENAS#9]
Dear authors,

We're using Linear_Region_Collector  class to count the number of linear regions in our network. However, it always returns the same result(batch size * sample_batch). Could be please give us some information about the suitable way of using it?

**Comment by chenwydj** [comment]
Hi @Yasaman-Haghighi,

Thank you for your interest in our work!

Deep NNs typically have a very large number of linear regions. To see the difference of NNs, you may want to forward a larger number of samples, or use smaller NNs (e.g. reduce #channels).

Hope that helps!
